# Generated by Django 2.2.3 on 2019-07-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kickstarer_Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backers', models.IntegerField()),
                ('blurb', models.CharField(max_length=135)),
                ('pleged', models.FloatField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
