# Generated by Django 2.2.3 on 2019-07-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kickstarer_Campaign',
            new_name='Kickstarter_Campaign',
        ),
    ]
