# Generated by Django 2.2.3 on 2019-07-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190730_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kickstarter_campaign',
            old_name='pleged',
            new_name='pledged',
        ),
    ]
