# Generated by Django 2.1.5 on 2019-07-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190726_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickstartercampaign',
            name='kickstarter_site_id',
            field=models.IntegerField(default=-1),
        ),
    ]
