# Generated by Django 2.1.4 on 2018-12-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entry_text', models.TextField()),
                ('rateing', models.IntegerField()),
            ],
        ),
    ]
