# Generated by Django 2.1.5 on 2019-07-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kickstartercampaign',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
