# Generated by Django 2.2.2 on 2019-06-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corperation',
            name='owners',
            field=models.ManyToManyField(null=True, to='api.Owner'),
        ),
    ]
