# Generated by Django 2.2.2 on 2019-06-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_corperation_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corperation',
            name='owners',
            field=models.ManyToManyField(to='api.Owner'),
        ),
    ]
